add api/v1/tasks
orevenat/TaskManager pull request #12
Opened 2021-11-28 16:57 UTC by orevenat

2021-11-28 18:06 UTC, greybutton requested changes

2021-11-28 18:06 UTC, greybutton commented on db/migrate/20211107164106_create_tasks.rb
> +      t.datetime :expired_at
миграции не изменяются, если нужно поменять поле, то пишем новую миграцию. почему решил поменять?

2021-11-28 18:06 UTC, greybutton commented on test/controllers/api/v1/tasks_controller_test.rb
> +    task_attributes = attributes_for(:task).except(:expired_at).
expired_at можно добавить в task_params

2021-11-28 18:06 UTC, greybutton commented on test/controllers/api/v1/tasks_controller_test.rb
> +    assigne = create(:developer)
опечатка небольшая assigne

2021-11-28 18:22 UTC, orevenat commented on db/migrate/20211107164106_create_tasks.rb
> +      t.datetime :expired_at
Вроде пока приложение не в продакшене, изменение схемы вместо лишней миграции допустимо?

2021-11-29 14:55 UTC, greybutton commented on db/migrate/20211107164106_create_tasks.rb
> +      t.datetime :expired_at
скорее что один разрабатываешь допускает такое, но если команда какая то была, то даже без прода уже не стоит так делать)

2021-11-29 14:56 UTC, greybutton approved these changes
поправил миграцию, а схему нет) Поправь плис, чтобы одинаково было. Аппрув поставлю

2021-11-30 07:37 UTC, merged